### ISSUE TITLE
[Feature Request] Mujoco integration

### ISSUE THREAD

**Issue by Trinkle23897** [sail-sg/envpool#59]
https://github.com/openai/gym/tree/master/gym/envs/mujoco

Env List:

- [x] Ant-v4 (#74)
- [x] HalfCheetah-v4 (#75)
- [x] Hopper-v4 (#76)
- [x] Humanoid-v4 (#77)
- [x] HumanoidStandup-v4 (#78)
- [x] InvertedDoublePendulum-v4 (@Benjamin-eecs, #83)
- [x] InvertedPendulum-v4 (#79)
- [x] Pusher-v4 (#82)
- [x] Reacher-v4 (#81)
- [x] Swimmer-v4 (#80)
- [x] Walker2d-v4 (@Benjamin-eecs, #86)
- [x] add other options to align with gym (#93)

Road Map:

- [x] Get comfortable with current codebase, go through https://envpool.readthedocs.io/en/latest/pages/env.html and add a toy environment by yourself locally;
- [x] Download Mujoco and run on your local machine [1] [5], try with different env settings and see the actual behavior;
- [x] Go through their code [1] [2] (I think it's better to go through both openai and deepmind versions, but only use deepmind's solution as reference), understand their ctype APIs and what we can use to bind with EnvPool APIs [3];
- [x] Integrate only one game and let it work;
- [x] Add some unit tests (good to submit the first PR here);
- [x] Integrate other environments (submit another PR) and related tests.

Resources:
1. https://github.com/openai/mujoco-py 
2. https://github.com/deepmind/dm_control/tree/master/dm_control/mujoco 
3. https://github.com/deepmind/mujoco/blob/main/doc/programming.rst
4. It is quite similar with Atari games which we have already integrated: https://github.com/mgbellemare/Arcade-Learning-Environment
5. First install gym and mujoco, then run with
```python
import gym
env = gym.make("Ant-v3")
env.reset()
for _ in range(10):
  env.step(env.action_space.sample())
  env.render()
```
6. https://github.com/ikostrikov/gym_dmc/blob/master/compare.py a checker

**Comment by kevinzakka** [comment]
Hello, this PR looks super exciting. Out of curiosity, do you have a sense of how hard it would be to port over a dm_control composer [Task](https://github.com/deepmind/dm_control/blob/main/dm_control/composer/task.py) / [Environment](https://github.com/deepmind/dm_control/blob/main/dm_control/composer/environment.py) to this API? Those include many more hooks that get called at every env step. Wondering if I could take a stab at it and if you have any thoughts!

**Comment by Trinkle23897** [comment]
Hi @kevinzakka, are you referring to #62? Currently I have no idea but we can have a discussion together to figure it out!

**Comment by kevinzakka** [comment]
Yup, along those lines! And yeah, would be interested in chatting about it :)

**Comment by Trinkle23897** [comment]
Just send an email.

**Comment by kevinzakka** [comment]
Hi @Trinkle23897 , apologies for missing the reply. I didn't receive any email, should I start one?

**Comment by Trinkle23897** [comment]
Sure, you can pin both of us and we'll send you the when2meet link.

**Comment by Trinkle23897** [comment]
@kevinzakka is zakka@berkeley.edu the right email for you? My email is trinkle23897@gmail.com

**Comment by kevinzakka** [comment]
Found it, thanks @Trinkle23897 !

**Comment by Trinkle23897** [comment]
@kevinzakka just release the newest benchmark result here: https://envpool.readthedocs.io/en/latest/pages/benchmark.html
